### ISSUE TITLE
MultiversX new namespace does not conform to CAIP-2

### ISSUE THREAD

**Issue by alexandru-g** [multiversx/mx-sdk-js-wallet-connect-provider#20]
The WalletConnect v2 new namespace used in this repo (multiversx) does not conform to the CAIP-2 standard, which is mandatory according to the v2 protocol:

- https://docs.walletconnect.com/2.0/specs/clients/sign/namespaces#14-chains-must-be-caip-2-compliant
- https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md

**Comment by radumojic** [comment]
Hello,

We noticed that too, and we are updating the MultiversX namespace from `multiversx` to `mvx` to be compliant with CAIP-2. 

The methods will also be prefixed with `mvx_*` instead of `multiversx_*`

The changes are already in progress in the xPortal App and once the new version is released on both platforms, a new version of the wallet-connect-provider signing provider will be released.

Since the WalletConnect libraries don't enforce the CAIP-2 compliance for now, xPortal will be backwards compatible with the previus namespaces for a while.

**Comment by radumojic** [comment]
The latest release ( `@multiversx/sdk-wallet-connect-provider@2.3.0` ) updated the namespace to the CAIP-2 compliant `mvx` namespace

Also the methods are now prefixed by mvx_*

```
mvx_signTransaction
mvx_signTransactions
mvx_signMessage
mvx_signLoginToken
```

xPortal will still work with the previous namespaces, but this was a necessary step to have a stable base for further developments in this area.

Thank you for notifying us !
